CREATE DATABASE NintendoSwitch;
USE NintendoSwitch;

CREATE TABLE usuario (
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nomeUsuario VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
dataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP
);

